name: Run Cypress Tests

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run

      - name: Send Slack notification
        if: always()
        uses: actions/github-script@v4
        with:
          script: |
            const webhookURL = "https://hooks.slack.com/services/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";
            const message = {
              text: `Cypress tests finished with status: ${{ job.status }}`
            };
            await fetch(webhookURL, {
              method: "POST",
              headers: {
                "Content-type": "application/json"
              },
              body: JSON.stringify(message)
            });
